name: 'Repo has new commits'
description: 'Checks if the repo has new commits'
inputs:
  # repoURL:  # id of input
  #   description: 'The repo address'
  #   required: true
  #   default: ''
  # branch:
  #   description: 'The name of the branch'
  #   required: true
  #   default: 'main'
  interval:  # id of input
    description: 'The interval in seconds'
    required: false
    default: 86400
outputs:
  has-updates: # id of output
    description: 'true the repo has updates, otherwise false'
runs:
  using: 'composite'
  steps:
    - name: Display input params
      run: |
        echo "repoURL: ${{ github.repository }}"
        echo "interval: ${{ inputs.interval }}"
      shell: bash

    - name: Activity check
      run: |
        date=curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s https://api.github.com/repos/${{ github.repository }}/commits | jq -r '[.[] | select(.author.login)][0]' | jq -r '.commit.author.date'
        timestamp=$(date --utc -d "$date" +%s)
        days=$(( ( $(date --utc +%s) - $timestamp ) / ${{ inputs.interval }} ))

        echo "Repository activity : $timestamp $days"
        alive=0

        if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
          echo "[WARNING] Ignoring activity limits : workflow triggered manually"
          alive=1
        else
          if [ $days -gt 1 ]; then
            echo "[WARNING] Repository activity : $days days ago"
          else
            echo "[WARNING] Repository not updated : event<${{ github.event_name }}> not allowed to modify stale repository"
          fi
        fi

        if [ $alive -eq 1 ]; then
          echo ::ste-output name=has-updates::true
        else
          echo ::ste-output name=has-updates::false
        fi
      shell: bash