name: Test action

on:
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Execute Action
        id: test-action
#        uses: ./
        uses: actiwaredevelopment/action-io-repo-updated@v0.1
        with:
          # repoURL: ${{ env.repoURL }}
          token: ${{ secrets.GITHUB_TOKEN }}
          interval: 86000

      - name: Echo Results
#        if: steps.ShouldRunScheduledBuild.outputs.ShouldRunScheduledBuild == 'true'
        run: echo "The value is ${{ steps.test-action.outputs.has-updates }}"